title: "ITC Conference"
source: _source

collections:
    congresses:
        title: Congresses
        output: True
    about-itc:
        title: About ITC
        output: True
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "about-itc"
        values:
            sidebar: "about-itc"

# deployment
host: 127.0.0.1
port: 4000
