title: "ITC Conference"
#source: _source
paginate: 10
paginate_path: "/news/page:num/"
baseurl: "/website-itc-conference"

exclude: [ "Gemfile", "Gemfile.lock", "scripts" ]

collections:
    congresses:
        title: Congresses
        output: True
        url: /congresses.html
    about-itc:
        title: About ITC
        output: True
        url: /
    specialist-seminars:
        title: Specialist Seminars
        output: True
        url: /specialist-seminars.html
    posts:
        title: News
        url: /news/
    itc-library:
        output: True
        title: ITC Publications
        url: /itc-library.html

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "about-itc"
        values:
            sidebar: "about-itc"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            type: "itc-library"
        values:
            layout: "library"
            sidebar: "itc-library"
            sprite: final-rgb_small-149x69.png

# deployment
host: 127.0.0.1
port: 4000
