title: "ITC Conference"
source: _source

collections:
    congresses:
        title: Congresses
        output: True
        url: /congresses.html
    about-itc:
        title: About ITC
        output: True
        url: /
    specialist-seminars:
        title: Specialist Seminars
        output: True
        url: /specialist-seminars.html
    posts:
        title: News
        url: /news.html

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "about-itc"
        values:
            sidebar: "about-itc"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

# deployment
host: 127.0.0.1
port: 4000
