title: "ITC Conference"
baseurl: ""
domain: "https://itc-conference.org"

# News were removed.
# To enable again: uncomment the following 2 lines, remove "news" and "_posts" entry
# from exclude list, uncomment respective lines in "collections" and "defaults",
# and uncomment respective lines in _layouts/default.html for sidebar entries.
# paginate: 10
# paginate_path: "/news/page:num/"

exclude: [ "README.md", "Gemfile", "Gemfile.lock", "vendor", "scripts", "news", "_posts" ]
theme: null
plugins:
    - jekyll-seo-tag

collections:
    congresses:
        title: Congresses
        output: True
        url: /congresses.html
    about-itc:
        title: About ITC
        output: True
        url: /
    specialist-seminars:
        title: Specialist Seminars
        output: True
        url: /specialist-seminars.html
    # posts:
    #     title: News
    #     url: /news/
    itc-library:
        output: True
        title: ITC Publications
        url: /itc-library.html
    redirect:
        output: True
        permalink: /:name


defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "about-itc"
        values:
            sidebar: "about-itc"
    -
        scope:
            type: "itc-library"
        values:
            layout: "library"
            sidebar: "itc-library"
            sprite: final-rgb_small-149x69.png
    -
        scope:
            type: "redirect"
        values:
            layout: "redirect"
    # -
    #     scope:
    #         path: ""
    #         type: "posts"
    #     values:
    #         layout: "post"

# deployment
host: 127.0.0.1
port: 4000
